config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/update'

  get "admin" => "admin#index"
	put "admin/:id" => "admin#update"
	patch "admin/:id" => "admin#update"

  resources :grades
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "grades#index"  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    if user.nil?
      # if no user logged in, use a dummy user, see later
      user = User.new
    end
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :teacher
      can :manage, Grade
    elsif user.has_role? :student
      can :read, Grade, user_id: user.id
    end
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  resourcify
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :grades

  after_create :assign_role

  def assign_role
    add_role(:student)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize

  # get "admin"
  def index
  	@users = User.all
  end

  # put/patch "admin/:id"
  def update
    user = User.find(params[:id])
    user.remove_role user.roles.last # user only has one role
    user.add_role(:teacher)
    redirect_to '/admin'
  end

  private

  def authorize
    if !current_user.has_role? :admin
      render plain:"No access for you!"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.where(user: current_user) unless current_user.has_role?(:admin) || current_user.has_role?(:teacher)
    @ability = Ability.new(current_user)
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:letter_grade, :comment, :course, :user_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/admin/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <thead>
      <tr>
        <th>Email</th><th>Role</th>
      </tr>
    </thead>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.roles.last.name %></td>
      <td>
        <%= form_tag("/admin/" + user.id.to_s + "?role=teacher", method: :PUT) do %>
          <input type="submit" value="Make Teacher"/>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
def update
    user = User.find(params[:id])
    user.remove_role user.roles.last # user only has one role
    user.add_role(:teacher)
    redirect_to '/admin'
end

app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :letter_grade %>
    <%= form.text_field :letter_grade, id: :grade_letter_grade %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :grade_comment %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course, id: :grade_course %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :grade_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grades</h1>

<table>
  <thead>
    <tr>
      <th>Letter grade</th>
      <th>Comment</th>
      <th>Course</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @grades.each do |grade| %>
      <% if @ability.can? :read, grade, user_id: current_user.id %>
        <tr>
          <td><%= grade.letter_grade %></td>
          <td><%= grade.comment %></td>
          <td><%= grade.course %></td>
          <td><%= grade.user.email %></td>
          <td><%= link_to 'Show', grade %></td>
          <% if @ability.can? :manage, Grade %>
            <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
            <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.has_role? :admin %>
  <%= link_to 'New Grade', new_grade_path %>
<% end %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Letter grade:</strong>
  <%= @grade.letter_grade %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @grade.comment %>
</p>

<p>
  <strong>Course:</strong>
  <%= @grade.course %>
</p>

<p>
  <strong>User:</strong>
  <%= @grade.user.email %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gradecentral</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <p>
    <% if user_signed_in? %>
			<%= if !current_user.nil?
	      current_user.email + ' (' + current_user.roles.pluck(:name).join(",") + ')'
	    end%>
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
		<% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
			<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
		<% end %>
		</p>
    <%= yield %>
  </body>
</html>